server:
  port: 8001

spring:
  application:
    name: url-vault
  datasource:
    url: jdbc:sqlite:url_vault.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    ru.kniturkai.urlvault: INFO
    org.hibernate.SQL: WARN
